name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  playwrightTest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

  playwright-Run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: playwrightTest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
